[env]
PYO3_PYTHON = { value = "C:/Users/24070/AppData/Local/Programs/Python/Python313/python.exe" }
PATH = { value = "C:/Users/24070/AppData/Local/Programs/Python/Python313/DLLs;C:/Users/24070/AppData/Local/Programs/Python/Python313;${env:PATH}" }